name: Backend-Cloverage

on:
  workflow_dispatch:

jobs:
  be-linter-cloverage:
    # don't run this workflow on a cron for forks
    if: ${{ github.event_name != 'schedule' || github.repository == 'metabase/metabase' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - name: Prepare back-end environment
        uses: ./.github/actions/prepare-backend
        with:
          m2-cache-key: "cloverage"
      - name: Build static viz frontend
        run: yarn build-static-viz
      - name: Collect the test coverage
        run: clojure -X:dev:ci:ee:ee-dev:test:cloverage
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/coverage/codecov.json
          flags: back-end
