name: Build for the official Metabase release
run-name: Build ${{ inputs.version }} for release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Metabase version (e.g. v0.46.3)'
        type: string
        required: true
      commit:
        description: 'A full-length commit SHA-1 hash'
        required: true

jobs:
  build-uberjar-for-release:
    if: ${{ github.repository }} != 'metabase/metabase'
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    strategy:
      matrix:
        edition: [oss, ee]
    env:
      INTERACTIVE: false
    steps:
    - name: Fail early on the incorrect version format
      if: ${{ !(startsWith(inputs.version,'v0.') || startsWith(inputs.version,'v1.')) }}
      run: |
        echo "The version format is invalid!"
        echo "It must start with either 'v0.' or 'v1.'."
        echo "Please, try again."
        exit 1
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.commit }}
    - name: prepare release scripts
      run: cd release && yarn && yarn build
    - name: Get Release Version
      uses: actions/github-script@v6
      id: canonical_version
      with:
        result-encoding: string
        script: |
          const { isValidVersionString, getCanonicalVersion } = require('${{ github.workspace }}/release/dist/index.cjs');

          const version = '${{ inputs.version }}';
          const edition = '${{ matrix.edition }}';

          if (!isValidVersionString(version)) {
            throw new Error("The version format is invalid! It must start with either 'v0.' or 'v1.'.");
          }

          const canonical_version = getCanonicalVersion(version, edition);

          console.log("The canonical version of this Metabase", process.env.EDITION, "edition is", canonical_version);
          return canonical_version;

    - name: Prepare front-end environment
      uses: ./.github/actions/prepare-frontend

    - name: Prepare back-end environment
      uses: ./.github/actions/prepare-backend

    - name: Build Metabase ${{ steps.canonical_version.outputs.result }}
      run: ./bin/build.sh :edition :${{ matrix.edition }} :version ${{ steps.canonical_version.outputs.result }}

    - name: Store commit's SHA-1 hash
      run:  echo ${{ inputs.commit }} > COMMIT-ID
      shell: bash
    - run: mv ./target/uberjar/metabase.jar ./metabase.jar
    - name: Calculate SHA256 checksum
      run: sha256sum ./metabase.jar > SHA256.sum
      shell: bash
    - name: Upload JARs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: metabase-${{ matrix.edition }}-${{ inputs.commit }}-uberjar
        path: |
          ./metabase.jar
          ./COMMIT-ID
          ./SHA256.sum
