name: Automatically mark milestone

on:
  push:
    branches:
      - release-x.**

jobs:
  mark-milestone:
    name: automatically set milestone
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          sparse-checkout: release
      - name: Prepare build scripts
        run: cd ${{ github.workspace }}/release && yarn && yarn build
      - uses: actions/github-script@v7
        with:
          script: | # js
            const { setMilestoneForCommits } = require('${{ github.workspace }}/release/dist/index.cjs');
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const branchName = '${{ github.ref }}';
            const commitMessage = '${{ github.event.head_commit.message }}';

            console.log({
              branchName,
              commitMessage,
              context: JSON.stringify(context, null, 2),
            });

            await setMilestoneForCommits({
              github,
              owner,
              repo,
              branchName,
              commitMessages: [commitMessage],
            });


