name: o401

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
jobs:
  o401:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/script@v7
        with:
          script: | # js
            const content = await fetch('https://infopanel.org/info/data/jokes.php')
              .then(res => res.json())
              .catch(console.error);

            const { setup, punchline } = content;

            const body = `\n\n
            <details>
              <summary>${setup}</summary>
              ${punchline}
            </details>
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body,
            }).catch(console.error);


