name: Release 1b - Auto Patch
run-name: Patch Release ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Major Metabase version (e.g. 45, 52, 68)'
        type: string
        required: true
  schedule:
    - cron: '0 7 * * 1-5' # every weekday at 8am/9am Central European Time

jobs:
  start-message:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: release
      - name: Prepare build scripts
        run: cd ${{ github.workspace }}/release && yarn && yarn build
      - name: Send build start message
        uses: actions/github-script@v7
        with:
          script: | # js
            const {
              getLatestGreenCommit,
              getNextPatchVersion,
            } = require('${{ github.workspace }}/release/dist/index.cjs');

            // Don't forget to update this for the next major release 🤞
            const AUTO_RELEASE_VERSIONS = [49, 50];

            async function releasePatchFor(majorVersion) {
              const nextPatch = await getNextPatchVersion({
                github,
                owner: context.repo.owner,
                repo: context.repo.repo,
                majorVersion: CURRENT_VERSION,
              });

              const goodCommit = await getLatestGreenCommit({
                github,
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: `release-x.${CURRENT_VERSION}.x`,
              });

              if (nextPatch && goodCommit) {
                await github.rest.actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: 'tag-for-release.yml',
                  ref: 'refs/heads/master',
                  inputs: {
                    commit: goodCommit,
                    version: nextPatch,
                    auto: true,
                  }
                });
              } else {
                console.log(
                  'No new patch version or no green commit found',
                  { nextPatch, goodCommit }
                );
              }
            }

            if (context.eventName === 'workflow_dispatch') {
              const inputVersion = Number('${{ inputs.version }}');

              if (typeof version !== 'number') {
                throw new Error('Invalid version number', '${{ inputs.version }}');
              }

              await releasePatchFor(inputVersion);
            } else { // scheduled release of AUTO_RELEASE_VERSIONS
              await Promise.all(AUTO_RELEASE_VERSIONS.map(releasePatchFor));
            }
